#!/usr/bin/python
import pytest
import os
import logging
from sfvs.nvme import nvme
import inspect
import time

@pytest.fixture(scope='module')
def hostname():
    cmd = "cat /etc/hostname"
    result = os.popen(cmd)
    host_name = result.read().strip().upper()
    logging.info("host_name at testbed is {}".format(host_name))
    result.close()
    return host_name

@pytest.fixture(scope="function", autouse=True)
def script(request):
    # skip empty tests
    sourcecode = inspect.getsourcelines(request.function)[0]
    if 'pass' in sourcecode[-1] and len(sourcecode) < 3:
        pytest.skip("empty test function")
    # measure test time, and set random seed by time
    start_time = time.time()
    yield
    logging.info("test duration: %.3f sec" % (time.time()-start_time))

@pytest.fixture(scope="module")
def nvme0():
    host = nvme.Host.enumerate()[0]
    ctrl = host.controller.enumerate()[0]
    ns = ctrl.enumerate_namespace()[0]
    ctrl.open()
    ns.open()
    logging.info("---ctrl open, ns open----")
    yield ctrl,ns
    ctrl.close()
    ns.close()
    logging.info("---ns close, ctrl close----")
    # files = os.listdir(os.getcwd())
    # for item in files:
    #     if '.log' in item:
    #         os.system('rm {}'.format(item))
    # logging.debug("clear read file and write file generated by case")